services:
  web:
    build: .
    ports:
      - '127.0.0.1:6180:80'
    user: www-data
    volumes:
      - ./passwords.csv:/var/www/passwords.csv:ro
      - ./user.sqlite:/var/www/user.sqlite
      - ./id_ed25519:/var/www/id_ed25519:ro
